services:
  traefik:
    image: traefik:3.5.2
    command:
      - --log.level=DEBUG
      - --accesslog=false
      - --accesslog.fields.defaultmode=keep
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --certificatesresolvers.acme.acme.httpchallenge=true
      - --certificatesresolvers.acme.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.acme.acme.email=you@rjchicago.com
      - --certificatesresolvers.acme.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    restart: unless-stopped

  www-web:
    image: rjchicago/rjchicago-llc-web:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.www-web.rule=Host(`www.rjchicago.com`) || Host(`rjchicago.com`)
      - traefik.http.routers.www-web.entrypoints=websecure
      - traefik.http.routers.www-web.tls=true
      - traefik.http.routers.www-web.tls.certresolver=acme
      - traefik.http.services.www-web.loadbalancer.server.port=3000
    restart: unless-stopped
  
  www-api:
    image: rjchicago/rjchicago-llc-api:latest
    environment:
      - PORT=4000
      - NODE_ENV=production
      - CORS_ORIGIN=https://www.rjchicago.com,https://rjchicago.com
    labels:
      - traefik.enable=true
      - traefik.http.routers.www-api.rule=(Host(`www.rjchicago.com`) || Host(`rjchicago.com`)) && PathPrefix(`/api`)
      - traefik.http.routers.www-api.entrypoints=websecure
      - traefik.http.routers.www-api.tls=true
      - traefik.http.routers.www-api.tls.certresolver=acme
      - traefik.http.routers.www-api.middlewares=api-strip
      - traefik.http.middlewares.api-strip.stripprefix.prefixes=/api
      - traefik.http.services.www-api.loadbalancer.server.port=4000
    restart: unless-stopped

  cman:
    image: rjchicago/cman-web:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.cman.rule=Host(`cman.rjchicago.com`)
      - traefik.http.routers.cman.entrypoints=websecure
      - traefik.http.routers.cman.tls=true
      - traefik.http.routers.cman.tls.certresolver=acme
      - traefik.http.services.cman.loadbalancer.server.port=80
    restart: unless-stopped